
services:
  - type: web
    name: expense-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true    # Render generates a random value
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString

databases:
  - name: expense-tracker-db
    plan: free